version: '3.3'

services:
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'db_featweb'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '1234'
       MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - database:/var/lib/mysql
  web:
    image: featweb:0.0.1
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DJANGO_SUPERUSER_USERNAME: 'root'
      DJANGO_SUPERUSER_EMAIL: 'feat-web@renesas.com'
      DJANGO_SUPERUSER_PASSWORD: '1234'
    volumes:
      - app:/var/lib/app
    ports:
      - "8000:8000"
volumes:
  database:
  app:

