version: '3.8'

services:
  localhost:
    image: mysql:5.7.22
    restart: always
    ports:
      - '33066:3306'
    environment:
       MYSQL_DATABASE: 'db_featweb'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '1234'
       MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - .dbdata:/var/lib/mysql
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"