# Generated by Django 3.2 on 2021-04-14 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('board_i2c_addess', models.TextField()),
                ('board_name', models.TextField()),
                ('power_status', models.BooleanField(default=False)),
                ('switch_status', models.BooleanField(default=False)),
                ('mode_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardFarm',
            fields=[
                ('farm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.TextField()),
                ('host_ip_address', models.TextField()),
                ('host_user', models.TextField()),
                ('host_ssh_key', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feat_web_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Board_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('action', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feat_web_app.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feat_web_app.boardfarm'),
        ),
    ]
