# Generated by Django 3.2 on 2021-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0010_rename_board_i2c_addess_board_board_i2c_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfarm',
            name='farm_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardfarm',
            name='status',
            field=models.TextField(default='Unavailable'),
        ),
    ]
