# Generated by Django 3.2 on 2021-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0011_auto_20210428_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfarm',
            name='farm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
