# Generated by Django 3.2 on 2021-05-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0012_alter_boardfarm_farm_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='Board',
        ),
        migrations.AlterModelTable(
            name='board_log',
            table='Board_Log',
        ),
        migrations.AlterModelTable(
            name='boardfarm',
            table='BoardFarm',
        ),
    ]
