# Generated by Django 3.2 on 2021-05-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0017_alter_board_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board_log',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
