# Generated by Django 3.2 on 2021-05-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0018_auto_20210519_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feat_web_app.board'),
        ),
    ]
