# Generated by Django 3.2 on 2021-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0019_alter_board_log_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
