# Generated by Django 3.2 on 2021-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0020_alter_board_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardfarm',
            old_name='host_ssh_key',
            new_name='password',
        ),
    ]
