# Generated by Django 3.2 on 2021-06-11 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0022_alter_board_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
