# Generated by Django 3.2 on 2021-06-11 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0024_alter_board_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
