# Generated by Django 3.2 on 2021-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0035_auto_20210616_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(default='14:17:00'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='board_log',
            table='board_log',
        ),
        migrations.AlterModelTable(
            name='boardfarm',
            table='boarfarm',
        ),
    ]
