# Generated by Django 3.2 on 2021-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0036_auto_20210616_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(default='14:24:05'),
        ),
        migrations.AlterModelTable(
            name='boardfarm',
            table='boardfarm',
        ),
    ]
