# Generated by Django 3.2 on 2021-06-17 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0037_auto_20210616_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feat_web_app.boardfarm'),
        ),
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(default='21:17:41'),
        ),
        migrations.AlterField(
            model_name='boardfarm',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='boardfarm',
            name='status',
            field=models.TextField(default='Unavailable'),
        ),
    ]
