# Generated by Django 3.2 on 2021-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0040_auto_20210617_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_log',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board_log',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boardfarm',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
