# Generated by Django 3.2 on 2021-06-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0041_auto_20210618_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardfarm',
            old_name='password',
            new_name='host_password',
        ),
    ]
