# Generated by Django 3.2 on 2021-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_web_app', '0042_rename_password_boardfarm_host_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfarm',
            name='host_script_location',
            field=models.TextField(default=''),
        ),
    ]
